#!/bin/sh

exec > /var/log/late_command.log 2>&1

set -x

DI_REPO="http://g0v.github.com/d-i/precise/"

. /etc/default/locale
jockey-text -a --no-dbus
apt-get install --yes $(check-language-support)
oem-config-prepare --quiet
wget ${DI_REPO}/sources.list -O /etc/apt/sources.list

# node.js ppa
apt-add-repository -y ppa:chris-lea/node.js 

apt-get update

apt-get install -y nodejs npm
